<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validacion[
<!ELEMENT especie (nombre,familia,distribucion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT familia (#PCDATA)>
<!ELEMENT distribucion (distribucion+)>
<!ELEMENT zona (#PCDATA)>


<!ATTLIST especie estado (sin-peligro | amenazado | extinto) "sin-peligro">
<!ATTLIST nombre nombre-cientifico CDATA #REQUIRED>
]>
<especie estado="amenazado">
    <nombre nombre-cientifico="Monachus monachus">Foca monje</nombre>
    <familia>Phocidae </familia>
    <distribucion>
        <zona>Costa Atlantica</zona>
        <zona>Costa Mediterranea</zona>
    </distribucion>
</especie>